import Head from "next/head";
import Buttons from "src/pages/components/Buttons";
import Cards from "src/pages/components/Cards";
import Header from "src/pages/components/Header";
import Logo from "src/pages/components/Logo";
import styles from "src/styles/Home.module.css";

export default function About() {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header title="about" />

        <Logo />
        <Buttons />
        <Cards />
      </main>
    </>
  );
}
