import Head from "next/head";
import { useCallback, useEffect, useState } from "react";
import Header from "src/pages/components/Header";
import styles from "src/styles/Home.module.css";

const Home = () => {
  const [posts, setPosts] = useState([]);

  const getPosts = useCallback(async () => {
    const json = await (
      await fetch("https://jsonplaceholder.typicode.com/posts")
    ).json();
    setPosts(json);
  }, []);

  useEffect(() => {
    getPosts();
  }, [getPosts]);

  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title="index" />
      <main className={styles.main}>
        {posts.length > 0 ? (
          <ol>
            {posts.map((post) => {
              return <li key={post.id}>{post.title}</li>;
            })}
          </ol>
        ) : null}
      </main>
    </>
  );
};
export default Home;
