import Head from "next/head";
import Cards from "src/pages/components/Cards";
import Header from "src/pages/components/Header";
import Logo from "src/pages/components/Logo";
import styles from "src/styles/Home.module.css";

const Home = (props) => {
  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header title="index" />

        <Logo />
        <div className={styles.flex}>
          {props.isShow ? (
            <div className={styles.thirteen}>
              <h1>{props.count}</h1>
            </div>
          ) : null}
          <button onClick={props.handleClick}>CountUp</button>
          <button onClick={props.handleDisplay}>
            {props.isShow ? "表示" : "非表示"}
          </button>

          <button onClick={props.handleAdd}>追加</button>
          <input type="text" value={props.text} onChange={props.handleText} />
          <ul>
            {props.array.map((item) => {
              return <li key={item}>{item}</li>;
            })}
          </ul>
        </div>
        <Cards />
      </main>
    </>
  );
};
export default Home;
